# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5044314e2f40f906c8bd40bc384575f702140a7f05555ccfc1fcc4152b2e59e03c5c3fe336042a72d8cc217e5ede411da281e15d044437a8fa0e81b447b5a11

test:
  secret_key_base: e7b51a050bbbc21ebd6f64f00225909b7fac2545cd2facee3217a7fb9e601bc8298064b15f1225484a2b928e67dbbe7a6719d7d3fd058e2d1dee0139a0799b79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
